// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mala_sampler_cpp
List mala_sampler_cpp(arma::vec init_x, Function U, Function grad_u, double step_size, int n_iter, double beta);
RcppExport SEXP _LangevinFlow_mala_sampler_cpp(SEXP init_xSEXP, SEXP USEXP, SEXP grad_uSEXP, SEXP step_sizeSEXP, SEXP n_iterSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type init_x(init_xSEXP);
    Rcpp::traits::input_parameter< Function >::type U(USEXP);
    Rcpp::traits::input_parameter< Function >::type grad_u(grad_uSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(mala_sampler_cpp(init_x, U, grad_u, step_size, n_iter, beta));
    return rcpp_result_gen;
END_RCPP
}
// ula_sampler_cpp
arma::mat ula_sampler_cpp(arma::vec init_x, Function grad_u, double step_size, int n_iter, double beta);
RcppExport SEXP _LangevinFlow_ula_sampler_cpp(SEXP init_xSEXP, SEXP grad_uSEXP, SEXP step_sizeSEXP, SEXP n_iterSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type init_x(init_xSEXP);
    Rcpp::traits::input_parameter< Function >::type grad_u(grad_uSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(ula_sampler_cpp(init_x, grad_u, step_size, n_iter, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LangevinFlow_mala_sampler_cpp", (DL_FUNC) &_LangevinFlow_mala_sampler_cpp, 6},
    {"_LangevinFlow_ula_sampler_cpp", (DL_FUNC) &_LangevinFlow_ula_sampler_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_LangevinFlow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
