# Partial Identification with Auxiliary Moment Restrictions

Code and numerical results accompanying the paper **"Partial
Identification with Auxiliary Moment Restrictions."**

**Authors**
- Arie Beresteanu — arie@pitt.edu
- Behrooz Moosavi Ramezanzadeh — behroozmoosavi@pitt.edu

The paper can be found by searching "Partial Identification with
Auxiliary Moment Restrictions" on arXiv or Google Scholar.

## What this repository contains

The paper's numerical illustration (Section 3) and its supplementary
appendix material (Appendix B/C) are all generated by one notebook,
`code/PI_CODE.ipynb`, using a CPS ASEC data extract built by a separate
notebook, `data/CPSdata.ipynb`. Every figure in the paper, and every
number reported or checked in the text, is reproducible from these two
notebooks alone.

## Repository structure

```
.
├── README.md                          <- you are here
├── code/
│   ├── PI_CODE.ipynb                  <- main analysis notebook
│   └── README.md                      <- what each block does, in order
├── data/
│   ├── CPSdata.ipynb                  <- pulls and cleans the CPS extract
│   ├── cps2020_v1.csv                 <- the resulting data file
│   ├── README.md                      <- data provenance and construction
│   └── VARIABLES.md                   <- data dictionary, every column
└── results/
    ├── figures_main/                  <- figures for the paper's main text
    ├── figures_appendix/              <- figures for the paper's appendix
    ├── results_summary.csv            <- every numerical result, in one file
    └── README.md                      <- which figure/number is which
```

## How to reproduce everything, in order

1. **Data** (only needed once, or to refresh the extract): open
   `data/CPSdata.ipynb`. It requires a Census Bureau API key (see
   `data/README.md`) and produces `data/cps2020_v1.csv`. A copy of this
   file is already included in the repository, so this step can be
   skipped if you only want to reproduce the analysis.
2. **Analysis**: copy `data/cps2020_v1.csv` into `code/`, then open and
   run `code/PI_CODE.ipynb` top to bottom. This regenerates every figure
   into `results/figures_main/` and `results/figures_appendix/`, and
   writes every numerical result used in the paper to
   `results/results_summary.csv`.
3. See `code/README.md` for what each block of the notebook corresponds
   to in the paper's theory (Section 2), and `results/README.md` for
   which output file corresponds to which figure in the paper.

## Requirements

```
numpy
pandas
scipy
matplotlib
requests        (data/CPSdata.ipynb only)
```

## Questions

For questions about the paper or this code, contact the authors at the
emails above.
