# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mala_sampler_cpp <- function(init_x, U, grad_u, step_size, n_iter, beta) {
    .Call(`_LangevinFlow_mala_sampler_cpp`, init_x, U, grad_u, step_size, n_iter, beta)
}

ula_sampler_cpp <- function(init_x, grad_u, step_size, n_iter, beta) {
    .Call(`_LangevinFlow_ula_sampler_cpp`, init_x, grad_u, step_size, n_iter, beta)
}

