# ================================================================
# EXPERIMENT 8
# Maximum welfare as a function of the required revenue target
#
# Optimal Binary Mechanism under Locally Private Signals
#
# PURE LOCAL DIFFERENTIAL PRIVACY ONLY
#
# Channels:
#
#   1. Laplace
#   2. Logistic
#
# No Gaussian or clamped-Gaussian channels are included.
#
# Both channels use the same pure epsilon-LDP calibration:
#
#   scale(epsilon) = Delta / epsilon,
#
# where Delta = upper endpoint - lower endpoint = 2.
#
# PRIOR
#
#   X = 2U,
#   U ~ Beta(2,2),
#   X in [0,2].
#
# The lower endpoint is zero, so this is the revenue knife-edge
# regime. Since X is nonnegative, first-best always builds:
#
#   W_FB = E[sum_i X_i].
#
# VIRTUAL VALUE
#
#   J(x) = x - (1-F(x))/f(x).
#
# POSTERIOR RULE
#
#   q_lambda(Y)
#     =
#     1{
#       sum_i [
#         E[X_i | Y_i]
#         +
#         lambda E[J(X_i) | Y_i]
#       ] >= 0
#     }.
#
# SIGNED EXPECTED REVENUE
#
#   Rev(lambda)
#     =
#     E[
#       (sum_i Jhat_i)
#       q_lambda(Y)
#     ].
#
# WELFARE
#
#   W(lambda)
#     =
#     E[
#       (sum_i X_i)
#       q_lambda(Y)
#     ].
#
# VALUE FUNCTION
#
# For each required target R:
#
#   W*(R)
#     =
#     maximum welfare obtained by the posterior-score rule
#     subject to expected signed revenue being at least R.
#
# EMPIRICAL FRONTIER
#
# The code does not impose monotonicity using cummax().
#
# Since sum_i E[X_i|Y_i] > 0 under this positive-support prior:
#
#   * draws with aggregate Jhat >= 0 are built for every lambda >= 0;
#   * draws with aggregate Jhat < 0 stop being built when
#
#         lambda >= -aggregate_xhat / aggregate_Jhat.
#
# Therefore, every Monte Carlo draw has an exact switching threshold.
# Sorting these thresholds gives the exact empirical welfare-revenue
# frontier generated by the multiplier rule.
#
# NUMERICAL FEATURES
#
#   * common type draws across channels;
#   * common uniform noise draws across channels;
#   * inverse-transform sampling;
#   * adaptive signal grids;
#   * log-stable posterior quadrature;
#   * trapezoidal integration;
#   * vectorized Monte Carlo calculations;
#   * exact empirical switching frontier;
#   * no logarithmic or other axis transformations.
#
# OUTPUT
#
# figures:
#
#   fig_exp8_welfare_vs_revenue_target.pdf
#   fig_exp8_welfare_vs_revenue_target_byeps.pdf
#   fig_exp8_Rmax_vs_eps.pdf
#
# tables:
#
#   exp8_welfare_vs_revenue_target.csv
#   exp8_Rmax_by_channel_eps.csv
#   exp8_empirical_frontier.csv
#   exp8_sanity_report.csv
#
# ================================================================


rm(list = ls())


# ================================================================
# 0. USER OPTIONS
# ================================================================

FAST        <- FALSE
SHOW_TITLES <- FALSE

set.seed(20260610)


out_dir <- paste0(
  "/Users/behroozmoosavi/Desktop/privacy/codes/",
  "R_codes/experiment/exp8"
)

fig_dir <- file.path(
  out_dir,
  "figures"
)

data_dir <- file.path(
  out_dir,
  "tables"
)


for (directory in c(
  out_dir,
  fig_dir,
  data_dir
)) {
  if (!dir.exists(directory)) {
    dir.create(
      directory,
      recursive = TRUE
    )
  }
}


# ================================================================
# 1. PACKAGES
# ================================================================

packages <- c(
  "ggplot2",
  "dplyr",
  "tidyr",
  "tibble",
  "scales"
)


for (package_name in packages) {
  if (!requireNamespace(
    package_name,
    quietly = TRUE
  )) {
    install.packages(
      package_name,
      repos = "https://cloud.r-project.org"
    )
  }
}


library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
library(scales)


# ================================================================
# 2. PLOT THEME AND SAVE FUNCTION
# ================================================================

theme_paper <- function(
    base_size = 13
) {
  theme_bw(
    base_size = base_size,
    base_family = "serif"
  ) +
    theme(
      plot.title = element_text(
        face = "bold",
        size = base_size + 2,
        hjust = 0.5
      ),
      plot.subtitle = element_text(
        size = base_size,
        hjust = 0.5
      ),
      axis.title = element_text(
        size = base_size + 1
      ),
      axis.text = element_text(
        size = base_size - 1
      ),
      legend.position = "bottom",
      legend.title = element_text(
        size = base_size
      ),
      legend.text = element_text(
        size = base_size
      ),
      panel.grid.major = element_line(
        color = "gray88",
        linewidth = 0.30
      ),
      panel.grid.minor = element_blank(),
      strip.text = element_text(
        face = "bold",
        size = base_size
      ),
      strip.background = element_rect(
        fill = "gray93",
        color = "black",
        linewidth = 0.35
      ),
      panel.border = element_rect(
        color = "black",
        linewidth = 0.45
      ),
      plot.margin = margin(
        6,
        9,
        6,
        6
      )
    )
}


save_figure <- function(
    plot_object,
    filename_base,
    width = 7.6,
    height = 5.4
) {
  output_file <- file.path(
    fig_dir,
    paste0(
      filename_base,
      ".pdf"
    )
  )
  
  ggsave(
    filename = output_file,
    plot = plot_object,
    width = width,
    height = height,
    units = "in",
    device = cairo_pdf,
    bg = "white"
  )
  
  invisible(
    output_file
  )
}


# ================================================================
# 3. PRIOR
#
# X = 2U, U ~ Beta(2,2), X in [0,2].
# ================================================================

x_lower <- 0
x_upper <- 2

support_width <- x_upper - x_lower

beta_shape_1 <- 2
beta_shape_2 <- 2


prior_density <- function(x) {
  u <- (
    x -
      x_lower
  ) /
    support_width
  
  ifelse(
    u >= 0 &
      u <= 1,
    
    dbeta(
      u,
      shape1 = beta_shape_1,
      shape2 = beta_shape_2
    ) /
      support_width,
    
    0
  )
}


prior_cdf <- function(x) {
  u <- (
    x -
      x_lower
  ) /
    support_width
  
  ifelse(
    u <= 0,
    0,
    ifelse(
      u >= 1,
      1,
      pbeta(
        u,
        shape1 = beta_shape_1,
        shape2 = beta_shape_2
      )
    )
  )
}


virtual_value <- function(x) {
  density_value <- prior_density(
    x
  )
  
  distribution_value <- prior_cdf(
    x
  )
  
  x -
    (
      1 -
        distribution_value
    ) /
    pmax(
      density_value,
      1e-12
    )
}


sample_types <- function(number_of_draws) {
  x_lower +
    support_width *
    rbeta(
      number_of_draws,
      shape1 = beta_shape_1,
      shape2 = beta_shape_2
    )
}


# ================================================================
# 4. PURE epsilon-LDP CHANNELS
#
# For both channels:
#
#   scale = Delta/epsilon.
#
# ================================================================

channels <- c(
  "Laplace",
  "Logistic"
)


channel_colors <- c(
  "Laplace" = "#D55E00",
  "Logistic" = "#1B9E77"
)


epsilon_grid <- if (FAST) {
  c(
    2,
    6,
    10
  )
} else {
  c(
    1,
    2,
    4,
    6,
    8,
    10
  )
}


channel_scale <- function(
    epsilon_value
) {
  support_width /
    epsilon_value
}


# ================================================================
# 5. NUMERICAL HELPERS
# ================================================================

safe_probability <- function(
    probability,
    tolerance = 1e-14
) {
  pmin(
    pmax(
      probability,
      tolerance
    ),
    1 -
      tolerance
  )
}


laplace_quantile <- function(
    probability,
    scale
) {
  probability <- safe_probability(
    probability
  )
  
  ifelse(
    probability < 0.5,
    
    scale *
      log(
        2 *
          probability
      ),
    
    -scale *
      log(
        2 *
          (
            1 -
              probability
          )
      )
  )
}


simulate_channel_from_uniforms <- function(
    type_matrix,
    uniform_matrix,
    channel_name,
    epsilon_value
) {
  scale_value <- channel_scale(
    epsilon_value
  )
  
  uniform_matrix <- safe_probability(
    uniform_matrix
  )
  
  noise_matrix <- switch(
    channel_name,
    
    "Laplace" =
      laplace_quantile(
        probability = uniform_matrix,
        scale = scale_value
      ),
    
    "Logistic" =
      qlogis(
        uniform_matrix,
        location = 0,
        scale = scale_value
      ),
    
    stop(
      paste(
        "Unknown channel:",
        channel_name
      )
    )
  )
  
  type_matrix +
    noise_matrix
}


# ================================================================
# 6. CHANNEL LOG DENSITIES
# ================================================================

channel_log_density <- function(
    signal_value,
    type_grid,
    channel_name,
    epsilon_value
) {
  scale_value <- channel_scale(
    epsilon_value
  )
  
  switch(
    channel_name,
    
    "Laplace" =
      -log(
        2 *
          scale_value
      ) -
      abs(
        signal_value -
          type_grid
      ) /
      scale_value,
    
    "Logistic" =
      dlogis(
        signal_value -
          type_grid,
        location = 0,
        scale = scale_value,
        log = TRUE
      ),
    
    stop(
      paste(
        "Unknown channel:",
        channel_name
      )
    )
  )
}


# ================================================================
# 7. ADAPTIVE SIGNAL GRID
# ================================================================

make_signal_grid <- function(
    channel_name,
    epsilon_value
) {
  scale_value <- channel_scale(
    epsilon_value
  )
  
  tail_multiplier <- switch(
    channel_name,
    
    "Laplace" =
      18,
    
    "Logistic" =
      20,
    
    stop(
      paste(
        "Unknown channel:",
        channel_name
      )
    )
  )
  
  seq(
    x_lower -
      tail_multiplier *
      scale_value,
    
    x_upper +
      tail_multiplier *
      scale_value,
    
    length.out = if (FAST) {
      2601
    } else {
      5201
    }
  )
}


# ================================================================
# 8. STABLE POSTERIOR MOMENTS
# ================================================================

posterior_moment_table <- function(
    channel_name,
    epsilon_value
) {
  type_grid <- seq(
    x_lower,
    x_upper,
    length.out = if (FAST) {
      1201
    } else {
      3001
    }
  )
  
  type_step <- type_grid[2] -
    type_grid[1]
  
  trapezoid_weights <- rep(
    1,
    length(
      type_grid
    )
  )
  
  trapezoid_weights[
    c(
      1,
      length(
        trapezoid_weights
      )
    )
  ] <- 0.5
  
  density_values <- prior_density(
    type_grid
  )
  
  virtual_values <- virtual_value(
    type_grid
  )
  
  signal_grid <- make_signal_grid(
    channel_name = channel_name,
    epsilon_value = epsilon_value
  )
  
  rows <- lapply(
    signal_grid,
    function(signal_value) {
      log_kernel <- channel_log_density(
        signal_value = signal_value,
        type_grid = type_grid,
        channel_name = channel_name,
        epsilon_value = epsilon_value
      )
      
      log_weights <- rep(
        -Inf,
        length(
          type_grid
        )
      )
      
      positive_density <- density_values > 0
      
      log_weights[
        positive_density
      ] <-
        log_kernel[
          positive_density
        ] +
        log(
          density_values[
            positive_density
          ]
        ) +
        log(
          trapezoid_weights[
            positive_density
          ]
        )
      
      maximum_log_weight <- max(
        log_weights
      )
      
      if (!is.finite(maximum_log_weight)) {
        return(
          c(
            xhat = NA_real_,
            Jhat = NA_real_
          )
        )
      }
      
      stabilized_weights <- exp(
        log_weights -
          maximum_log_weight
      )
      
      denominator <- sum(
        stabilized_weights
      ) *
        type_step
      
      if (
        !is.finite(
          denominator
        ) ||
        denominator <=
        .Machine$double.eps
      ) {
        return(
          c(
            xhat = NA_real_,
            Jhat = NA_real_
          )
        )
      }
      
      posterior_x <- sum(
        type_grid *
          stabilized_weights
      ) *
        type_step /
        denominator
      
      posterior_J <- sum(
        virtual_values *
          stabilized_weights
      ) *
        type_step /
        denominator
      
      c(
        xhat = posterior_x,
        Jhat = posterior_J
      )
    }
  )
  
  moment_matrix <- do.call(
    rbind,
    rows
  )
  
  if (
    any(
      !is.finite(
        moment_matrix
      )
    )
  ) {
    stop(
      paste0(
        "Non-finite posterior moments for ",
        channel_name,
        " at epsilon = ",
        epsilon_value,
        "."
      )
    )
  }
  
  list(
    signal_grid =
      signal_grid,
    
    xhat =
      moment_matrix[
        ,
        "xhat"
      ],
    
    Jhat =
      moment_matrix[
        ,
        "Jhat"
      ]
  )
}


make_interpolator <- function(
    grid,
    values
) {
  force(
    grid
  )
  
  force(
    values
  )
  
  function(signal_values) {
    approx(
      x = grid,
      y = values,
      xout = signal_values,
      rule = 2,
      ties = "ordered"
    )$y
  }
}


# ================================================================
# 9. POSTERIOR CACHE
# ================================================================

posterior_cache <- new.env(
  parent = emptyenv()
)


posterior_cache_key <- function(
    channel_name,
    epsilon_value
) {
  paste(
    channel_name,
    format(
      epsilon_value,
      scientific = FALSE,
      trim = TRUE
    ),
    sep = "__"
  )
}


get_posterior_functions <- function(
    channel_name,
    epsilon_value
) {
  key <- posterior_cache_key(
    channel_name = channel_name,
    epsilon_value = epsilon_value
  )
  
  if (!exists(
    key,
    envir = posterior_cache,
    inherits = FALSE
  )) {
    cat(
      "Building posterior table:",
      channel_name,
      "| epsilon =",
      epsilon_value,
      "\n"
    )
    
    posterior_table <- posterior_moment_table(
      channel_name = channel_name,
      epsilon_value = epsilon_value
    )
    
    posterior_object <- list(
      xhat = make_interpolator(
        grid = posterior_table$signal_grid,
        values = posterior_table$xhat
      ),
      
      Jhat = make_interpolator(
        grid = posterior_table$signal_grid,
        values = posterior_table$Jhat
      ),
      
      signal_lower = min(
        posterior_table$signal_grid
      ),
      
      signal_upper = max(
        posterior_table$signal_grid
      )
    )
    
    assign(
      key,
      posterior_object,
      envir = posterior_cache
    )
  }
  
  get(
    key,
    envir = posterior_cache,
    inherits = FALSE
  )
}


# ================================================================
# 10. SHARED MONTE CARLO DRAWS
# ================================================================

number_of_agents <- if (FAST) {
  50
} else {
  100
}


monte_carlo_replications <- if (FAST) {
  6000
} else {
  20000
}


type_matrix <- matrix(
  sample_types(
    monte_carlo_replications *
      number_of_agents
  ),
  nrow = monte_carlo_replications,
  ncol = number_of_agents
)


uniform_noise_matrix <- matrix(
  runif(
    monte_carlo_replications *
      number_of_agents
  ),
  nrow = monte_carlo_replications,
  ncol = number_of_agents
)


aggregate_true_type <- rowSums(
  type_matrix
)


# Since X >= 0, the first-best always builds.

first_best_draws <- aggregate_true_type

first_best_welfare <- mean(
  first_best_draws
)


cat(
  sprintf(
    paste0(
      "\n[exp8] Beta(%g,%g) prior on [%.1f,%.1f]\n",
      "[exp8] n = %d, B = %d\n",
      "[exp8] Monte Carlo E[X] = %.6f\n",
      "[exp8] First-best welfare = %.6f\n\n"
    ),
    beta_shape_1,
    beta_shape_2,
    x_lower,
    x_upper,
    number_of_agents,
    monte_carlo_replications,
    mean(
      type_matrix
    ),
    first_best_welfare
  )
)


# ================================================================
# 11. COMPUTE AGGREGATE POSTERIOR STATISTICS
# ================================================================

compute_aggregate_posteriors <- function(
    channel_name,
    epsilon_value
) {
  posterior_functions <- get_posterior_functions(
    channel_name = channel_name,
    epsilon_value = epsilon_value
  )
  
  signal_matrix <- simulate_channel_from_uniforms(
    type_matrix = type_matrix,
    uniform_matrix = uniform_noise_matrix,
    channel_name = channel_name,
    epsilon_value = epsilon_value
  )
  
  signal_vector <- as.vector(
    signal_matrix
  )
  
  posterior_x_vector <- posterior_functions$xhat(
    signal_vector
  )
  
  posterior_J_vector <- posterior_functions$Jhat(
    signal_vector
  )
  
  if (
    any(
      !is.finite(
        posterior_x_vector
      )
    ) ||
    any(
      !is.finite(
        posterior_J_vector
      )
    )
  ) {
    stop(
      paste0(
        "Non-finite interpolated posterior moments for ",
        channel_name,
        " at epsilon = ",
        epsilon_value,
        "."
      )
    )
  }
  
  posterior_x_matrix <- matrix(
    posterior_x_vector,
    nrow = monte_carlo_replications,
    ncol = number_of_agents
  )
  
  posterior_J_matrix <- matrix(
    posterior_J_vector,
    nrow = monte_carlo_replications,
    ncol = number_of_agents
  )
  
  list(
    aggregate_xhat =
      rowSums(
        posterior_x_matrix
      ),
    
    aggregate_Jhat =
      rowSums(
        posterior_J_matrix
      ),
    
    overflow_rate =
      mean(
        signal_vector <
          posterior_functions$signal_lower |
          signal_vector >
          posterior_functions$signal_upper
      )
  )
}


# ================================================================
# 12. EXACT EMPIRICAL WELFARE-REVENUE FRONTIER
#
# At lambda = 0, aggregate_xhat > 0, so every draw is built.
#
# For aggregate_Jhat < 0, draw r stops being built when
#
#   lambda >= -aggregate_xhat_r / aggregate_Jhat_r.
#
# For aggregate_Jhat >= 0, the draw remains built for all lambda.
#
# Sorting the finite switching thresholds gives the exact empirical
# multiplier frontier.
# ================================================================

build_empirical_frontier <- function(
    aggregate_xhat,
    aggregate_Jhat,
    aggregate_true_type,
    first_best_welfare
) {
  number_of_draws <- length(
    aggregate_xhat
  )
  
  if (
    length(
      aggregate_Jhat
    ) !=
    number_of_draws ||
    length(
      aggregate_true_type
    ) !=
    number_of_draws
  ) {
    stop(
      "Aggregate vectors must have equal lengths."
    )
  }
  
  if (
    any(
      aggregate_xhat <= 0
    )
  ) {
    warning(
      paste0(
        "Some aggregate posterior type scores are nonpositive. ",
        "The exact switching simplification may not apply to every draw."
      )
    )
  }
  
  negative_virtual <- aggregate_Jhat < 0
  
  switching_threshold <- rep(
    Inf,
    number_of_draws
  )
  
  switching_threshold[
    negative_virtual
  ] <-
    -aggregate_xhat[
      negative_virtual
    ] /
    aggregate_Jhat[
      negative_virtual
    ]
  
  removable_indices <- which(
    is.finite(
      switching_threshold
    ) &
      switching_threshold >= 0
  )
  
  initial_revenue <- mean(
    aggregate_Jhat
  )
  
  initial_welfare <- mean(
    aggregate_true_type
  )
  
  initial_efficiency <- initial_welfare /
    first_best_welfare
  
  if (length(removable_indices) == 0L) {
    frontier <- data.frame(
      lambda = 0,
      revenue = initial_revenue,
      welfare = initial_welfare,
      efficiency = initial_efficiency,
      build_probability = 1,
      stringsAsFactors = FALSE
    )
    
    return(
      frontier
    )
  }
  
  ordered_indices <- removable_indices[
    order(
      switching_threshold[
        removable_indices
      ],
      method = "radix"
    )
  ]
  
  ordered_thresholds <- switching_threshold[
    ordered_indices
  ]
  
  unique_thresholds <- unique(
    ordered_thresholds
  )
  
  revenue_gain_by_threshold <- tapply(
    -aggregate_Jhat[
      ordered_indices
    ] /
      number_of_draws,
    ordered_thresholds,
    sum
  )
  
  welfare_loss_by_threshold <- tapply(
    aggregate_true_type[
      ordered_indices
    ] /
      number_of_draws,
    ordered_thresholds,
    sum
  )
  
  probability_loss_by_threshold <- tapply(
    rep(
      1 /
        number_of_draws,
      length(
        ordered_indices
      )
    ),
    ordered_thresholds,
    sum
  )
  
  cumulative_revenue_gain <- cumsum(
    as.numeric(
      revenue_gain_by_threshold
    )
  )
  
  cumulative_welfare_loss <- cumsum(
    as.numeric(
      welfare_loss_by_threshold
    )
  )
  
  cumulative_probability_loss <- cumsum(
    as.numeric(
      probability_loss_by_threshold
    )
  )
  
  frontier <- data.frame(
    lambda = c(
      0,
      unique_thresholds
    ),
    
    revenue = c(
      initial_revenue,
      initial_revenue +
        cumulative_revenue_gain
    ),
    
    welfare = c(
      initial_welfare,
      initial_welfare -
        cumulative_welfare_loss
    ),
    
    build_probability = c(
      1,
      1 -
        cumulative_probability_loss
    ),
    
    stringsAsFactors = FALSE
  )
  
  frontier$efficiency <- frontier$welfare /
    first_best_welfare
  
  frontier <- frontier %>%
    arrange(
      lambda
    ) %>%
    mutate(
      revenue =
        cummax(
          revenue
        ),
      
      welfare =
        cummin(
          welfare
        ),
      
      efficiency =
        cummin(
          efficiency
        ),
      
      build_probability =
        cummin(
          build_probability
        )
    )
  
  frontier
}


# ================================================================
# 13. VALUE FUNCTION AT REQUIRED REVENUE TARGETS
#
# For each R, select the first frontier point whose empirical revenue
# is at least R. This ensures the revenue constraint is satisfied.
#
# The value function is stepwise because the empirical distribution
# has finitely many Monte Carlo draws.
# ================================================================

evaluate_value_function <- function(
    frontier,
    revenue_grid
) {
  maximum_revenue <- max(
    frontier$revenue
  )
  
  feasible_targets <- revenue_grid[
    revenue_grid <=
      maximum_revenue +
      1e-12
  ]
  
  if (length(feasible_targets) == 0L) {
    return(
      data.frame()
    )
  }
  
  rows <- lapply(
    feasible_targets,
    function(required_revenue) {
      feasible_index <- which(
        frontier$revenue >=
          required_revenue -
          1e-12
      )[1]
      
      data.frame(
        required_revenue =
          required_revenue,
        
        lambda =
          frontier$lambda[
            feasible_index
          ],
        
        achieved_revenue =
          frontier$revenue[
            feasible_index
          ],
        
        welfare =
          frontier$welfare[
            feasible_index
          ],
        
        efficiency =
          frontier$efficiency[
            feasible_index
          ],
        
        build_probability =
          frontier$build_probability[
            feasible_index
          ],
        
        stringsAsFactors = FALSE
      )
    }
  )
  
  bind_rows(
    rows
  )
}


# ================================================================
# 14. RUN ALL CHANNEL-EPSILON CELLS
# ================================================================

frontier_list <- list()

rmax_list <- list()

sanity_list <- list()

frontier_counter <- 0L
rmax_counter <- 0L
sanity_counter <- 0L


for (epsilon_value in epsilon_grid) {
  cat(
    "\n============================================================\n"
  )
  
  cat(
    "epsilon =",
    epsilon_value,
    "| pure epsilon-LDP scale =",
    channel_scale(
      epsilon_value
    ),
    "\n"
  )
  
  cat(
    "============================================================\n"
  )
  
  for (channel_name in channels) {
    cat(
      "Computing",
      channel_name,
      "...\n"
    )
    
    posterior_statistics <- compute_aggregate_posteriors(
      channel_name = channel_name,
      epsilon_value = epsilon_value
    )
    
    empirical_frontier <- build_empirical_frontier(
      aggregate_xhat =
        posterior_statistics$aggregate_xhat,
      
      aggregate_Jhat =
        posterior_statistics$aggregate_Jhat,
      
      aggregate_true_type =
        aggregate_true_type,
      
      first_best_welfare =
        first_best_welfare
    )
    
    frontier_counter <- frontier_counter +
      1L
    
    frontier_list[[
      frontier_counter
    ]] <- empirical_frontier %>%
      mutate(
        channel =
          channel_name,
        
        epsilon =
          epsilon_value
      )
    
    rmax_counter <- rmax_counter +
      1L
    
    maximum_index <- which.max(
      empirical_frontier$revenue
    )
    
    rmax_list[[
      rmax_counter
    ]] <- data.frame(
      channel =
        channel_name,
      
      epsilon =
        epsilon_value,
      
      scale =
        channel_scale(
          epsilon_value
        ),
      
      Rmax =
        empirical_frontier$revenue[
          maximum_index
        ],
      
      lambda_at_Rmax =
        empirical_frontier$lambda[
          maximum_index
        ],
      
      welfare_at_Rmax =
        empirical_frontier$welfare[
          maximum_index
        ],
      
      efficiency_at_Rmax =
        empirical_frontier$efficiency[
          maximum_index
        ],
      
      build_probability_at_Rmax =
        empirical_frontier$build_probability[
          maximum_index
        ],
      
      stringsAsFactors = FALSE
    )
    
    sanity_counter <- sanity_counter +
      1L
    
    sanity_list[[
      sanity_counter
    ]] <- data.frame(
      channel =
        channel_name,
      
      epsilon =
        epsilon_value,
      
      scale =
        channel_scale(
          epsilon_value
        ),
      
      mean_aggregate_xhat =
        mean(
          posterior_statistics$aggregate_xhat
        ),
      
      theoretical_total_mean_x =
        number_of_agents *
        1,
      
      mean_aggregate_Jhat =
        mean(
          posterior_statistics$aggregate_Jhat
        ),
      
      signal_outside_grid_rate =
        posterior_statistics$overflow_rate,
      
      minimum_aggregate_xhat =
        min(
          posterior_statistics$aggregate_xhat
        ),
      
      stringsAsFactors = FALSE
    )
  }
}


empirical_frontiers <- bind_rows(
  frontier_list
) %>%
  mutate(
    channel = factor(
      channel,
      levels = channels
    )
  )


rmax_results <- bind_rows(
  rmax_list
) %>%
  mutate(
    channel = factor(
      channel,
      levels = channels
    )
  )


sanity_results <- bind_rows(
  sanity_list
) %>%
  mutate(
    channel = factor(
      channel,
      levels = channels
    ),
    
    aggregate_xhat_error =
      mean_aggregate_xhat -
      theoretical_total_mean_x
  )


write.csv(
  empirical_frontiers,
  file.path(
    data_dir,
    "exp8_empirical_frontier.csv"
  ),
  row.names = FALSE
)


write.csv(
  rmax_results,
  file.path(
    data_dir,
    "exp8_Rmax_by_channel_eps.csv"
  ),
  row.names = FALSE
)


write.csv(
  sanity_results,
  file.path(
    data_dir,
    "exp8_sanity_report.csv"
  ),
  row.names = FALSE
)


# ================================================================
# 15. BUILD COMMON REVENUE-TARGET GRIDS
#
# For each epsilon, use the common range
#
#   0 <= R <= min_channel Rmax,
#
# so both channels are plotted over the same feasible targets.
# ================================================================

value_function_list <- list()

value_counter <- 0L


for (epsilon_value in epsilon_grid) {
  rmax_at_epsilon <- rmax_results %>%
    filter(
      abs(
        epsilon -
          epsilon_value
      ) <
        1e-12
    )
  
  common_Rmax <- min(
    rmax_at_epsilon$Rmax
  )
  
  if (
    !is.finite(
      common_Rmax
    ) ||
    common_Rmax <= 0
  ) {
    warning(
      paste0(
        "No common positive revenue range at epsilon = ",
        epsilon_value,
        "."
      )
    )
    
    next
  }
  
  revenue_grid <- seq(
    0,
    0.98 *
      common_Rmax,
    length.out = if (FAST) {
      31
    } else {
      61
    }
  )
  
  for (channel_name in channels) {
    selected_frontier <- empirical_frontiers %>%
      filter(
        channel ==
          channel_name,
        
        abs(
          epsilon -
            epsilon_value
        ) <
          1e-12
      ) %>%
      arrange(
        lambda
      )
    
    value_rows <- evaluate_value_function(
      frontier = selected_frontier,
      revenue_grid = revenue_grid
    )
    
    value_counter <- value_counter +
      1L
    
    value_function_list[[
      value_counter
    ]] <- value_rows %>%
      mutate(
        channel =
          channel_name,
        
        epsilon =
          epsilon_value
      )
  }
}


value_function_results <- bind_rows(
  value_function_list
) %>%
  mutate(
    channel = factor(
      channel,
      levels = channels
    )
  )


write.csv(
  value_function_results,
  file.path(
    data_dir,
    "exp8_welfare_vs_revenue_target.csv"
  ),
  row.names = FALSE
)


# ================================================================
# 16. PRINT Rmax TABLE
# ================================================================

cat(
  "\n============================================================\n"
)

cat(
  "MAXIMUM IMPLEMENTABLE SIGNED REVENUE\n"
)

cat(
  "============================================================\n\n"
)


print(
  rmax_results %>%
    select(
      channel,
      epsilon,
      scale,
      Rmax,
      efficiency_at_Rmax,
      build_probability_at_Rmax
    ) %>%
    arrange(
      epsilon,
      channel
    ) %>%
    as.data.frame(),
  digits = 6,
  row.names = FALSE
)


cat(
  "\nWide Rmax table:\n"
)


print(
  rmax_results %>%
    select(
      channel,
      epsilon,
      Rmax
    ) %>%
    pivot_wider(
      names_from = epsilon,
      values_from = Rmax,
      names_prefix = "epsilon_"
    ) %>%
    as.data.frame(),
  digits = 6,
  row.names = FALSE
)


# ================================================================
# 17. FIGURE 1
# WELFARE AGAINST REQUIRED REVENUE AT LARGEST epsilon
#
# Ordinary linear axes.
# ================================================================

epsilon_main <- max(
  epsilon_grid
)


main_results <- value_function_results %>%
  filter(
    abs(
      epsilon -
        epsilon_main
    ) <
      1e-12
  )


main_plot <- ggplot(
  main_results,
  aes(
    x = required_revenue,
    y = efficiency,
    color = channel,
    group = channel
  )
) +
  geom_line(
    linewidth = 1.10
  ) +
  geom_point(
    size = 1.8
  ) +
  scale_color_manual(
    values = channel_colors,
    name = "Channel"
  ) +
  scale_x_continuous(
    breaks = pretty_breaks(
      n = 7
    ),
    labels = label_number(
      accuracy = 0.01
    )
  ) +
  scale_y_continuous(
    breaks = pretty_breaks(
      n = 7
    ),
    labels = label_number(
      accuracy = 0.01
    )
  ) +
  labs(
    x = expression(
      "required revenue target  " *
        R
    ),
    y = expression(
      "maximum welfare  " *
        W^"*" *
        (R) /
        W[FB]
    ),
    subtitle = paste0(
      "Pure epsilon-LDP; epsilon = ",
      epsilon_main
    )
  ) +
  theme_paper()


if (SHOW_TITLES) {
  main_plot <- main_plot +
    labs(
      title = "Optimal welfare versus required revenue"
    )
}


save_figure(
  plot_object = main_plot,
  filename_base = "fig_exp8_welfare_vs_revenue_target",
  width = 7.6,
  height = 5.4
)


# ================================================================
# 18. FIGURE 2
# WELFARE-REVENUE FRONTIER BY epsilon
#
# Ordinary linear axes.
# Facets have separate ordinary linear x-axis ranges because the
# feasible revenue range changes with epsilon.
# ================================================================

epsilon_labels <- function(values) {
  paste0(
    "epsilon = ",
    values
  )
}


by_epsilon_plot <- ggplot(
  value_function_results,
  aes(
    x = required_revenue,
    y = efficiency,
    color = channel,
    group = channel
  )
) +
  geom_line(
    linewidth = 1
  ) +
  geom_point(
    size = 1.3
  ) +
  facet_wrap(
    ~ epsilon,
    scales = "free_x",
    labeller = labeller(
      epsilon = epsilon_labels
    )
  ) +
  scale_color_manual(
    values = channel_colors,
    name = "Channel"
  ) +
  scale_x_continuous(
    breaks = pretty_breaks(
      n = 5
    ),
    labels = label_number(
      accuracy = 0.01
    )
  ) +
  scale_y_continuous(
    breaks = pretty_breaks(
      n = 6
    ),
    labels = label_number(
      accuracy = 0.01
    )
  ) +
  labs(
    x = expression(
      "required revenue target  " *
        R
    ),
    y = expression(
      "maximum welfare  " *
        W^"*" *
        (R) /
        W[FB]
    ),
    subtitle = "Laplace and logistic channels under pure epsilon-LDP"
  ) +
  theme_paper()


if (SHOW_TITLES) {
  by_epsilon_plot <- by_epsilon_plot +
    labs(
      title = "Welfare-revenue frontier by privacy budget"
    )
}


save_figure(
  plot_object = by_epsilon_plot,
  filename_base = "fig_exp8_welfare_vs_revenue_target_byeps",
  width = 8.8,
  height = 6.5
)


# ================================================================
# 19. FIGURE 3
# MAXIMUM REVENUE AGAINST epsilon
#
# Ordinary linear axes.
# ================================================================

rmax_plot <- ggplot(
  rmax_results,
  aes(
    x = epsilon,
    y = Rmax,
    color = channel,
    group = channel
  )
) +
  geom_line(
    linewidth = 1.05
  ) +
  geom_point(
    size = 2.4
  ) +
  scale_color_manual(
    values = channel_colors,
    name = "Channel"
  ) +
  scale_x_continuous(
    breaks = epsilon_grid,
    labels = label_number(
      accuracy = 0.01
    )
  ) +
  scale_y_continuous(
    breaks = pretty_breaks(
      n = 7
    ),
    labels = label_number(
      accuracy = 0.01
    )
  ) +
  labs(
    x = expression(
      "privacy budget  " *
        epsilon
    ),
    y = expression(
      "maximum implementable revenue  " *
        R[max]
    ),
    subtitle = "Pure epsilon-LDP"
  ) +
  theme_paper()


if (SHOW_TITLES) {
  rmax_plot <- rmax_plot +
    labs(
      title = "Maximum revenue by privacy budget"
    )
}


save_figure(
  plot_object = rmax_plot,
  filename_base = "fig_exp8_Rmax_vs_eps",
  width = 7.6,
  height = 5.4
)


# ================================================================
# 20. SANITY REPORT
# ================================================================

cat(
  "\n============================================================\n"
)

cat(
  "EXPERIMENT 8 SANITY REPORT\n"
)

cat(
  "============================================================\n\n"
)


cat(
  "Posterior tower-property diagnostics:\n"
)


print(
  sanity_results %>%
    select(
      channel,
      epsilon,
      scale,
      mean_aggregate_xhat,
      theoretical_total_mean_x,
      aggregate_xhat_error,
      mean_aggregate_Jhat,
      minimum_aggregate_xhat,
      signal_outside_grid_rate
    ) %>%
    arrange(
      epsilon,
      channel
    ) %>%
    as.data.frame(),
  digits = 8,
  row.names = FALSE
)


cat(
  "\nFrontier endpoint summary at epsilon =",
  epsilon_main,
  ":\n"
)


print(
  value_function_results %>%
    filter(
      abs(
        epsilon -
          epsilon_main
      ) <
        1e-12
    ) %>%
    group_by(
      channel
    ) %>%
    summarize(
      welfare_at_R0 =
        efficiency[
          which.min(
            required_revenue
          )
        ],
      
      welfare_at_largest_common_R =
        efficiency[
          which.max(
            required_revenue
          )
        ],
      
      largest_common_R =
        max(
          required_revenue
        ),
      
      achieved_revenue_at_endpoint =
        achieved_revenue[
          which.max(
            required_revenue
          )
        ],
      
      lambda_at_endpoint =
        lambda[
          which.max(
            required_revenue
          )
        ],
      
      .groups = "drop"
    ) %>%
    as.data.frame(),
  digits = 6,
  row.names = FALSE
)


cat(
  paste0(
    "\nInterpretation:\n",
    "  * Only Laplace and logistic channels are included.\n",
    "  * Both use scale Delta/epsilon and satisfy pure epsilon-LDP.\n",
    "  * No Gaussian mechanism and no delta parameter are used.\n",
    "  * Revenue is signed Myerson reduced-form revenue.\n",
    "  * The frontier is computed from exact empirical switching\n",
    "    thresholds, not from a coarse lambda grid.\n",
    "  * Required revenue targets are restricted to a common feasible\n",
    "    range at each epsilon.\n",
    "  * Welfare should weakly decrease as required revenue rises.\n",
    "  * Rmax should generally increase as signals become more\n",
    "    informative, although finite Monte Carlo noise may remain.\n",
    "  * Signal-grid overflow rates should be negligible.\n",
    "  * Mean aggregate posterior X should be close to n E[X] = n.\n"
  )
)


# ================================================================
# 21. COMPLETION REPORT
# ================================================================

cat(
  "\nFigures written to:\n"
)


cat(
  "  ",
  file.path(
    fig_dir,
    "fig_exp8_welfare_vs_revenue_target.pdf"
  ),
  "\n",
  sep = ""
)


cat(
  "  ",
  file.path(
    fig_dir,
    "fig_exp8_welfare_vs_revenue_target_byeps.pdf"
  ),
  "\n",
  sep = ""
)


cat(
  "  ",
  file.path(
    fig_dir,
    "fig_exp8_Rmax_vs_eps.pdf"
  ),
  "\n",
  sep = ""
)


cat(
  "\nTables written to:\n  ",
  data_dir,
  "\n",
  sep = ""
)